#!/bin/bash -e

PAUSE=true
if [[ $1 == "-n" ]] ; then
  PAUSE=false
  shift
fi

function docurl() {
  echo "curl $headers $@"
  if $PAUSE ; then read -s ; fi
  echo -n '==> '
  curl -s -H 'Content-Type: application/json' -H 'Accept: application/json' $headers "$@" | jq -r .
  echo ""
  echo ""
  if $PAUSE ; then read -s ; fi
}

base="http://localhost:8080/api"
case $1 in
    1)
	docurl $base/pets
	docurl $base/pets -X POST -d '{"tag": "dog", "name": "Snopy"}'
	docurl $base/pets -X POST -d '{"tag": "cat", "name": "Garfield"}'
	docurl $base/pets -X POST -d '{"tag": "rat", "name": "Remy"}'
	docurl $base/pets
	docurl $base/pets?tags=rat\&tags=dog
	docurl $base/pets/1 -X DELETE
	docurl $base/pets
	docurl $base/pets/0
	docurl $base/pets/1
	;;
    2)
	docurl $base/pets/0 -X PUT -d '{"tag": "dog", "name": "Snoopy"}'
	docurl $base/pets
	;;
esac
